name: SleepDemocracy
main: fi.gosu.mc.plugins.SleepDemocracy.SleepDemocracy
version: 1.0.1
author: Aikain
description: Minecraft plugin for democracy of sleeping
commands:
  sdtoggle:
    description: Change SleepDemocracy status ON/OFF
    permission: sleepdemocracy.sdtoggle
    usage: |
      /sdtoggle [ON|OFF]
      Example: /sdtoggle - Toggle plugin status
      Example: /sdtoggle ON - Turn on plugin
  sdset:
    description: Sets the percent of SleepDemocracy which required sleepers
    permission: sleepdemocracy.sdset
    usage: |
      /sdset <percent>
      Example: /sdset 40 - Needs 2 of 5 player to sleep
permissions:
  sleepdemocracy.*:
    description: Gives access to all SleepDemocracy command
    children:
      sleepdemocracy.sdtoggle: true
      sleepdemocracy.sdset: true
  sleepdemocracy.sdtoggle:
    description: Allow you change plugin status
    default: op
  sleepdemocracy.sdset:
    description: Allow you change plugin sleep percent
    default: op
